HEIGHT = 500
WIDTH = 500
FPS = 30

BOXUP = -50
BOXDOWN = HEIGHT+50
BOXLEFT = -50
BOXRIGHT = WIDTH+50

SIZE = 40
MOUSE_BOX_SIZE = 20
DEBUG_UPDATES = True
WALKING_SPEED = 10
PLAYER_JUMP_SPEED = 10
FALL_SPEED_CHANGE = -1.1
FALL_SPEED_CAP = -7

BLOCK_MIN_HEIGHT_TO_THREAT_AS_WALL = -21
GROUND_BLOCK_OFFSET = -8


